### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by jinukjin** [AdColony/AdColony-Android-SDK#65]
We're using adcolony in admob mediation.
It's occured crash only android 5.1.

![image](https://user-images.githubusercontent.com/10558327/67174419-ec1ad380-f3fc-11e9-9125-9d9fdd21bbce.png)
![image](https://user-images.githubusercontent.com/10558327/67174434-f5a43b80-f3fc-11e9-86f3-a335bb2b4d7b.png)

It's adcolony mediation sdk version in our project.

implementation 'androidx.appcompat:appcompat:1.1.0
api 'androidx.annotation:annotation:1.1.0'
api 'com.adcolony:sdk:3.3.11'
api 'com.google.ads.mediation:adcolony:3.3.11.0'

please check my crash issue.

**Comment by pchinn** [comment]
Hi @jinukjin,  We can investigate your crash.  Can you tell us which AdColony Zone ID your app was using when this crash occurred?  Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by brittmullen** [comment]
Fixed in 4.1.1
