### ISSUE TITLE
Always showing "getStreamVolume isRestricted mode = 0" log in console

### ISSUE THREAD

**Issue by nilabja1312** [AdColony/AdColony-Android-SDK#66]
I have recently added the Banner ads in my application by following demo application guven here. Since then the following log always comes 
```
"2019-10-22 12:34:27.962 10746-10746/com.wedoria.meverolearn D/AudioManager: getStreamVolume isRestricted mode = 0"
![adcolony](https://user-images.githubusercontent.com/13375519/67264608-3a95a400-f4c9-11e9-8a06-31ca65a496bd.png)



```

**Comment by pchinn** [comment]
Hi @nilabja1312,  We can investigate your issue.  Which Zone ID is your app using?  Do you get the same messages when you build our Banner [Demo](https://github.com/AdColony/AdColony-Android-SDK) app using your own App ID/Zone ID?   Please send us your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by pchinn** [comment]
Hi @nilabja1312 , Did you try building our Banner Demo app using your own App ID/Zone ID? Let us know your results. Please send us your information to support@adcolony.com and we will assist you directly. Thanks.
