### ISSUE TITLE
AdColony [WARNING]: Rewarded ad: show() called with no reward listener set.

### ISSUE THREAD

**Issue by luck-alex13** [AdColony/AdColony-Android-SDK#68]
Hi! Sometimes thehe is warning on logcat:
AdColony [WARNING]: Rewarded ad: show() called with no reward listener set.
Usually everything works fine. But sometimes when I try to play a video, I get such a log and the video does not play.

**Comment by pchinn** [comment]
Hi @luck-alex13,  We can help investigate your issue.  What is the zone ID you're using when this happens?  Also, do you get the same behavior when you build our [RewardedInterstitialDemo](https://github.com/AdColony/AdColony-Android-SDK/tree/master/Demos) app using your own App ID and Zone ID?   Please send us all your information to support@adcolony.com and we will assist you directly. Thanks.

**Comment by langthiennhai** [comment]
In my case, after the video has finished playing, the function below cannot be called.

    // (test, debug only)
     final private String APP_ID = "app185a7e71e1714831a49ec7";
     final private String ZONE_ID = "vz1fd5a8b2bf6841a0a4b826";




       // Create and set a reward listener
         AdColony.setRewardListener (new AdColonyRewardListener () {
             @Override
             public void onReward (AdColonyReward reward) {
                 // Query reward object for info here
                 Log.d (TAG, "onReward");
             }
         });

However, APP_ID, ZONE_ID of RewardedInterstitialDemo still work well.

Why is that? What I need to do? Will you please tell me. Thank you.

**Comment by pchinn** [comment]
Hi @langthiennhai,  We built and ran our [RewardedInterstitialDemo](https://github.com/AdColony/AdColony-Android-SDK/tree/master/Demos) app v4.1.1 with default test zone "vz1fd5a8b2bf6841a0a4b826", and logcat displayed the "onReward" log [message](https://drive.google.com/file/d/1tqsWj9K7j5x_wsZlIRto9MvPUDK3SBo_/view?usp=sharing).  Please send us your questions to support@adcolony.com and we will assist you directly. Thanks.

**Comment by langthiennhai** [comment]
Hi  AdColony Support Team

Please check for help with the case of APP_ID, ZONE_ID as below, do not
output "onReward" log message

final private String APP_ID = "appfbdcc64371e94c7096";
final private String ZONE_ID = "vz933cb2f6d34140be88";

Thank you.

**Comment by pchinn** [comment]
Hi @langthiennhai, Your zone is using server side callback url that is invalid. Please setup a proper server that gathers the url query params and returns a proper string (ie. 'vc_success') to AdColony. You'll find more info here: https://github.com/AdColony/AdColony-Android-SDK/wiki/Showing-Rewarded-Interstitial-Ads#server-side-rewards. Please send an email to support@adcolony.com and we will assist you directly. Thanks.
