### ISSUE TITLE
adColonyInterstitial show ! on a null object reference

### ISSUE THREAD

**Issue by saidmote3** [AdColony/AdColony-Android-SDK#69]
Hi AdColony, i want to use your lib in my project android studio, but i found this problems when Initialize Banner and Interstitial in same time, in 
case 1 : replaced initializing banner first and interstitial seconde, result : banner work but interstitial not working & give a null reference !
case 2 : replaced initialize Interstitilize to be first, result : interstitial work fine, but banner not.

**Comment by pchinn** [comment]
Hi @saidmote3 ,  Does this happen with both Zone IDs in Test mode?  Can you send us the exact 'null reference' log message  that you're seeing?  Please send us your information to support@adcolony.com and we will assist you directly. Thanks.
