### ISSUE TITLE
Keep getting onRequestNotFilled 

### ISSUE THREAD

**Issue by AviadKlein10** [AdColony/AdColony-Android-SDK#71]
Hi what can I do?
Can you not closed this issue and give a solution?

I've done everything from wiki as it say

**Comment by pchinn** [comment]
Hi @AviadKlein10,  Our Demo apps work fine.  Have you tried building our Demo [apps](https://github.com/AdColony/AdColony-Android-SDK) using your own **App ID** and **Zone ID**?  What was your results?  Please send us your results to support@adcolony.com and we will assist you directly. Thanks.

**Comment by Abhijith4124** [comment]
I am Facing the Same Issue on the Latest SDK. Is there a way to know the error Code or error Message?

**Comment by pchinn** [comment]
Hi @Abhijith4124 ,  The onRequestNotFilled means there was no ad fill at the time of your ad request. Have you tried building our [Demo ](https://github.com/AdColony/AdColony-Android-SDK) apps using your own **App ID** and **Zone ID**? What was your results?  Please send us your results to support@adcolony.com and we will assist you directly. Thanks.

**Comment by pchinn** [comment]
Hi @AviadKlein10, Are you still seeing  the *onRequestNotFilled* message?  Please send your response to support@adcolony.com and we will assist you directly. Thanks.

**Comment by Abhijith4124** [comment]
> Hi @Abhijith4124 , The onRequestNotFilled means there was no ad fill at the time of your ad request. Have you tried building our [Demo ](https://github.com/AdColony/AdColony-Android-SDK) apps using your own **App ID** and **Zone ID**? What was your results? Please send us your results to [support@adcolony.com](mailto:support@adcolony.com) and we will assist you directly. Thanks.

I am Using the Demo AppId and Zone id to load Ad. I am getting onRequestNotFilled no matter what the appid and zone id is

**Comment by pchinn** [comment]
Hi @Abhijith4124 We have more than one Demo app. Which Demo AppID and ZoneID did you use?  

Please send your response to **support@adcolony.com** and we will assist you directly. Thanks.

**Comment by AviadKlein10** [comment]
Hi
Thank you for your response.
I just tried using my AppID and ZoneID in your demo and still getting the
same error: onRequestNotFilled.

What should I do?

Thank you,
Aviad

‫בתאריך יום ה׳, 30 בינו׳ 2020 ב-17:35 מאת ‪pchinn‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by pchinn** [comment]
@Abhijith4124  As mentioned, the onRequestNotFilled means there was no ad fill at the time of your ad request.   Which Demo app did you use? What is your AppID and ZoneID?  For privacy,  please send your response to support@adcolony.com and we will assist you directly. Thanks.

**Comment by pchinn** [comment]
@AviadKlein10   As mentioned, the onRequestNotFilled means there was no ad fill at the time of your ad request.   Which Demo App did you use?  What is your AppID and ZoneID?  To avoid sharing your info to the public, please send us your results to support@adcolony.com and we will assist you directly. Thanks.

**Comment by jffs** [comment]
I get these error when want to show a banner ad.

**Comment by pchinn** [comment]
Hi @jffs, The onRequestNotFilled means there was no ad fill at the time of your ad request.  Please try your ad request again. If you want to test if your integration is correct, we suggest enabling your Zone to test mode, and our servers will return a test banner.  Thanks.

**Comment by pchinn** [comment]
HI @AviadKlein10  We received your Support email and our team will work with you directly.
