### ISSUE TITLE
Ads NoFill After Applying Proguard

### ISSUE THREAD

**Issue by Abhijith4124** [AdColony/AdColony-Android-SDK#73]
Hi,
After i add proguard it just returns No Fill error. In the logcat its given AdColony is disabled.

What Might be the problem?

**Comment by pchinn** [comment]
Hi @Abhijith4124,  Our Proguard setting are found [here](https://github.com/AdColony/AdColony-Android-SDK/wiki/Project-Setup#step-4-proguard-configuration).  Can you send us your entire logcat logs from the 'Configure' event through the 'AdColony is disabled' message'?   Also, which Zone ID are you using?  Please send us your information to support@adcolony.com and we will assist you directly. Thanks.
